name: simple_flags
description: Simple country flags component.
version: 1.0.0
homepage: https://zulfahmi.dev
publish_to: https://pub.zulfahmi.dev

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/simple_flags/assets/AD.png
    - packages/simple_flags/assets/AE.png
    - packages/simple_flags/assets/AF.png
    - packages/simple_flags/assets/AG.png
    - packages/simple_flags/assets/AI.png
    - packages/simple_flags/assets/AL.png
    - packages/simple_flags/assets/AM.png
    - packages/simple_flags/assets/AN.png
    - packages/simple_flags/assets/AO.png
    - packages/simple_flags/assets/AR.png
    - packages/simple_flags/assets/AS.png
    - packages/simple_flags/assets/AT.png
    - packages/simple_flags/assets/AU.png
    - packages/simple_flags/assets/AW.png
    - packages/simple_flags/assets/AZ.png
    - packages/simple_flags/assets/BA.png
    - packages/simple_flags/assets/BB.png
    - packages/simple_flags/assets/BD.png
    - packages/simple_flags/assets/BE.png
    - packages/simple_flags/assets/BF.png
    - packages/simple_flags/assets/BG.png
    - packages/simple_flags/assets/BH.png
    - packages/simple_flags/assets/BI.png
    - packages/simple_flags/assets/BJ.png
    - packages/simple_flags/assets/BL.png
    - packages/simple_flags/assets/BM.png
    - packages/simple_flags/assets/BN.png
    - packages/simple_flags/assets/BO.png
    - packages/simple_flags/assets/BR.png
    - packages/simple_flags/assets/BS.png
    - packages/simple_flags/assets/BT.png
    - packages/simple_flags/assets/BW.png
    - packages/simple_flags/assets/BY.png
    - packages/simple_flags/assets/BZ.png
    - packages/simple_flags/assets/CA.png
    - packages/simple_flags/assets/CC.png
    - packages/simple_flags/assets/CD.png
    - packages/simple_flags/assets/CF.png
    - packages/simple_flags/assets/CG.png
    - packages/simple_flags/assets/CH.png
    - packages/simple_flags/assets/CI.png
    - packages/simple_flags/assets/CK.png
    - packages/simple_flags/assets/CL.png
    - packages/simple_flags/assets/CM.png
    - packages/simple_flags/assets/CN.png
    - packages/simple_flags/assets/CO.png
    - packages/simple_flags/assets/CR.png
    - packages/simple_flags/assets/CU.png
    - packages/simple_flags/assets/CV.png
    - packages/simple_flags/assets/CW.png
    - packages/simple_flags/assets/CX.png
    - packages/simple_flags/assets/CY.png
    - packages/simple_flags/assets/CZ.png
    - packages/simple_flags/assets/DE.png
    - packages/simple_flags/assets/DJ.png
    - packages/simple_flags/assets/DK.png
    - packages/simple_flags/assets/DM.png
    - packages/simple_flags/assets/DO.png
    - packages/simple_flags/assets/DZ.png
    - packages/simple_flags/assets/EC.png
    - packages/simple_flags/assets/EE.png
    - packages/simple_flags/assets/EG.png
    - packages/simple_flags/assets/EH.png
    - packages/simple_flags/assets/ER.png
    - packages/simple_flags/assets/ES.png
    - packages/simple_flags/assets/ET.png
    - packages/simple_flags/assets/FI.png
    - packages/simple_flags/assets/FJ.png
    - packages/simple_flags/assets/FK.png
    - packages/simple_flags/assets/FM.png
    - packages/simple_flags/assets/FO.png
    - packages/simple_flags/assets/FR.png
    - packages/simple_flags/assets/GA.png
    - packages/simple_flags/assets/GB.png
    - packages/simple_flags/assets/GD.png
    - packages/simple_flags/assets/GE.png
    - packages/simple_flags/assets/GF.png
    - packages/simple_flags/assets/GG.png
    - packages/simple_flags/assets/GH.png
    - packages/simple_flags/assets/GI.png
    - packages/simple_flags/assets/GL.png
    - packages/simple_flags/assets/GM.png
    - packages/simple_flags/assets/GN.png
    - packages/simple_flags/assets/GP.png
    - packages/simple_flags/assets/GQ.png
    - packages/simple_flags/assets/GR.png
    - packages/simple_flags/assets/GT.png
    - packages/simple_flags/assets/GU.png
    - packages/simple_flags/assets/GW.png
    - packages/simple_flags/assets/GY.png
    - packages/simple_flags/assets/HK.png
    - packages/simple_flags/assets/HN.png
    - packages/simple_flags/assets/HR.png
    - packages/simple_flags/assets/HT.png
    - packages/simple_flags/assets/HU.png
    - packages/simple_flags/assets/ID.png
    - packages/simple_flags/assets/IE.png
    - packages/simple_flags/assets/IL.png
    - packages/simple_flags/assets/IM.png
    - packages/simple_flags/assets/IN.png
    - packages/simple_flags/assets/IO.png
    - packages/simple_flags/assets/IQ.png
    - packages/simple_flags/assets/IR.png
    - packages/simple_flags/assets/IS.png
    - packages/simple_flags/assets/IT.png
    - packages/simple_flags/assets/JE.png
    - packages/simple_flags/assets/JM.png
    - packages/simple_flags/assets/JO.png
    - packages/simple_flags/assets/JP.png
    - packages/simple_flags/assets/KE.png
    - packages/simple_flags/assets/KG.png
    - packages/simple_flags/assets/KH.png
    - packages/simple_flags/assets/KI.png
    - packages/simple_flags/assets/KM.png
    - packages/simple_flags/assets/KN.png
    - packages/simple_flags/assets/KP.png
    - packages/simple_flags/assets/KR.png
    - packages/simple_flags/assets/KW.png
    - packages/simple_flags/assets/KY.png
    - packages/simple_flags/assets/KZ.png
    - packages/simple_flags/assets/LA.png
    - packages/simple_flags/assets/LB.png
    - packages/simple_flags/assets/LC.png
    - packages/simple_flags/assets/LI.png
    - packages/simple_flags/assets/LK.png
    - packages/simple_flags/assets/LR.png
    - packages/simple_flags/assets/LS.png
    - packages/simple_flags/assets/LT.png
    - packages/simple_flags/assets/LU.png
    - packages/simple_flags/assets/LV.png
    - packages/simple_flags/assets/LY.png
    - packages/simple_flags/assets/MA.png
    - packages/simple_flags/assets/MC.png
    - packages/simple_flags/assets/MD.png
    - packages/simple_flags/assets/ME.png
    - packages/simple_flags/assets/MF.png
    - packages/simple_flags/assets/MG.png
    - packages/simple_flags/assets/MH.png
    - packages/simple_flags/assets/MK.png
    - packages/simple_flags/assets/ML.png
    - packages/simple_flags/assets/MM.png
    - packages/simple_flags/assets/MN.png
    - packages/simple_flags/assets/MO.png
    - packages/simple_flags/assets/MP.png
    - packages/simple_flags/assets/MQ.png
    - packages/simple_flags/assets/MR.png
    - packages/simple_flags/assets/MS.png
    - packages/simple_flags/assets/MT.png
    - packages/simple_flags/assets/MU.png
    - packages/simple_flags/assets/MV.png
    - packages/simple_flags/assets/MW.png
    - packages/simple_flags/assets/MX.png
    - packages/simple_flags/assets/MY.png
    - packages/simple_flags/assets/MZ.png
    - packages/simple_flags/assets/NA.png
    - packages/simple_flags/assets/NC.png
    - packages/simple_flags/assets/NE.png
    - packages/simple_flags/assets/NF.png
    - packages/simple_flags/assets/NG.png
    - packages/simple_flags/assets/NI.png
    - packages/simple_flags/assets/NL.png
    - packages/simple_flags/assets/NO.png
    - packages/simple_flags/assets/NP.png
    - packages/simple_flags/assets/NR.png
    - packages/simple_flags/assets/NU.png
    - packages/simple_flags/assets/NZ.png
    - packages/simple_flags/assets/OM.png
    - packages/simple_flags/assets/PA.png
    - packages/simple_flags/assets/PE.png
    - packages/simple_flags/assets/PF.png
    - packages/simple_flags/assets/PG.png
    - packages/simple_flags/assets/PH.png
    - packages/simple_flags/assets/PK.png
    - packages/simple_flags/assets/PL.png
    - packages/simple_flags/assets/PM.png
    - packages/simple_flags/assets/PN.png
    - packages/simple_flags/assets/PR.png
    - packages/simple_flags/assets/PS.png
    - packages/simple_flags/assets/PT.png
    - packages/simple_flags/assets/PW.png
    - packages/simple_flags/assets/PY.png
    - packages/simple_flags/assets/QA.png
    - packages/simple_flags/assets/RE.png
    - packages/simple_flags/assets/RO.png
    - packages/simple_flags/assets/RS.png
    - packages/simple_flags/assets/RU.png
    - packages/simple_flags/assets/RW.png
    - packages/simple_flags/assets/SA.png
    - packages/simple_flags/assets/SB.png
    - packages/simple_flags/assets/SC.png
    - packages/simple_flags/assets/SD.png
    - packages/simple_flags/assets/SE.png
    - packages/simple_flags/assets/SG.png
    - packages/simple_flags/assets/SH.png
    - packages/simple_flags/assets/SI.png
    - packages/simple_flags/assets/SK.png
    - packages/simple_flags/assets/SL.png
    - packages/simple_flags/assets/SM.png
    - packages/simple_flags/assets/SN.png
    - packages/simple_flags/assets/SO.png
    - packages/simple_flags/assets/SR.png
    - packages/simple_flags/assets/SS.png
    - packages/simple_flags/assets/ST.png
    - packages/simple_flags/assets/SV.png
    - packages/simple_flags/assets/SX.png
    - packages/simple_flags/assets/SY.png
    - packages/simple_flags/assets/SZ.png
    - packages/simple_flags/assets/TC.png
    - packages/simple_flags/assets/TD.png
    - packages/simple_flags/assets/TG.png
    - packages/simple_flags/assets/TH.png
    - packages/simple_flags/assets/TJ.png
    - packages/simple_flags/assets/TK.png
    - packages/simple_flags/assets/TL.png
    - packages/simple_flags/assets/TM.png
    - packages/simple_flags/assets/TN.png
    - packages/simple_flags/assets/TO.png
    - packages/simple_flags/assets/TR.png
    - packages/simple_flags/assets/TT.png
    - packages/simple_flags/assets/TV.png
    - packages/simple_flags/assets/TW.png
    - packages/simple_flags/assets/TZ.png
    - packages/simple_flags/assets/UA.png
    - packages/simple_flags/assets/UG.png
    - packages/simple_flags/assets/US.png
    - packages/simple_flags/assets/UY.png
    - packages/simple_flags/assets/UZ.png
    - packages/simple_flags/assets/VA.png
    - packages/simple_flags/assets/VC.png
    - packages/simple_flags/assets/VE.png
    - packages/simple_flags/assets/VG.png
    - packages/simple_flags/assets/VI.png
    - packages/simple_flags/assets/VN.png
    - packages/simple_flags/assets/VU.png
    - packages/simple_flags/assets/WF.png
    - packages/simple_flags/assets/WS.png
    - packages/simple_flags/assets/XK.png
    - packages/simple_flags/assets/YE.png
    - packages/simple_flags/assets/YT.png
    - packages/simple_flags/assets/ZA.png
    - packages/simple_flags/assets/ZM.png
    - packages/simple_flags/assets/ZW.png
