name: simple_settings
description: Simple settings component.
version: 1.0.0
homepage: https://zulfahmi.dev
publish_to: https://pub.zulfahmi.dev

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  shared_preferences: ^2.0.6

dev_dependencies:
  effective_dart: ^1.3.1
  mockito: ^5.0.0
  test: ^1.17.8
