name: simple_settings
description: Simple settings component.
version: 1.0.0
author: Zulfahmi Ahmad <zulfahmi93@outlook.com>
homepage: https://zulfahmi.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  shared_preferences: ^2.0.3

dev_dependencies:
  effective_dart: ^1.3.0
  mockito: ^5.0.0
  test: ^1.16.5
