name: simple_settings
description: Simple settings component.
version: 0.0.1
author: Zulfahmi Ahmad <zulfahmi93@outlook.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3

dev_dependencies:
  effective_dart: ^1.2.1
  flutter_test:
    sdk: flutter
