name: simple_logger
description: Simple logging service.
version: 1.0.0
author: Zulfahmi Ahmad <zulfahmi93@outlook.com>
homepage: https://zulfahmi.dev
publish_to: https://pub.zulfahmi.dev/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: ^2.0.2
  logging: ^1.0.1

dev_dependencies:
  build_runner: ^1.12.2
  effective_dart: ^1.3.1
  hive_generator: ^1.0.1
  test: ^1.16.8
