name: simple_http_client
description: Simple HTTP client component.
version: 1.0.0
homepage: https://zulfahmi.dev
publish_to: https://pub.zulfahmi.dev

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.1
  simple_extensions:
    hosted:
      name: simple_extensions
      url: https://pub.zulfahmi.dev
    version: '>=1.0.0 <2.0.0'
  simple_logger:
    hosted:
      name: simple_logger
      url: https://pub.zulfahmi.dev
    version: '>=1.0.0 <2.0.0'

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.17.8
