name: simple_validators
description: Object validators component.
version: 1.0.0
author: Zulfahmi Ahmad <zulfahmi93@outlook.com>
homepage: https://zulfahmi.dev

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.16.2
