name: simple_di
description: Simple dependency injection component.
version: 0.1.0
author: Zulfahmi Ahmad <zulfahmi93@outlook.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  effective_dart: ^1.2.4
